<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flare.Api\Flare.Api.csproj" />
    <ProjectReference Include="..\Flare.AlertWorker\Flare.AlertWorker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SourceMaps\Fixtures\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
