// Client for Flare.Api's Query API (search/aggregate) and live-tail WebSocket.
//
// Historically every `lib/*-api.ts` module hand-mirrored its TypeScript `interface`s
// against the matching `src/Flare.Api/Model/*.cs` + `Json/*JsonContext.cs` (camelCase
// properties, PascalCase string enums - `UseStringEnumConverter` without a naming policy
// leaves enum member names as-is) and decoded every response via `res.json()`. Phase 2 of
// docs-internal/investigations/memorypack-serialization-migration-scope.md replaces that
// convention, file by file, with MemoryPack's generated TypeScript decoders
// (`$lib/generated/memorypack/*.ts`, regenerated by `dotnet build` on Flare.Api - see
// `predev`/`prebuild`/`precheck` in package.json) sent/received via
// `MEMORYPACK_CONTENT_TYPE` below, plus a handful of hand-written classes
// (`$lib/memorypack/*.ts`) for DTOs MemoryPack's TypeScript generator can't emit itself
// (any type with a `DateTimeOffset` or `JsonElement` member - see that investigation doc's
// Phase 2 section for exactly why and the wire format verified for each). Every migrated
// function still returns/accepts this file's original hand-written interfaces unchanged -
// only what happens between the network and that shape is different - so no consumer
// outside `lib/` needs to change. A module not yet migrated still hand-mirrors its
// interfaces and calls `res.json()` exactly as before; check that module's own header
// comment for its current state.

import { env } from '$env/dynamic/public';
import { logAggregateGroupByFromString, logQlResultKindToString, resourceHealthToString, resourceStateToString } from '$lib/memorypack/enums';
import { LogFilter as GeneratedLogFilter, logFilterFromPlain } from '$lib/memorypack/LogFilter';
import { LogEventDto as GeneratedLogEventDto } from '$lib/memorypack/LogEventDto';
import { LogSearchRequest as GeneratedLogSearchRequest } from '$lib/memorypack/LogSearchRequest';
import { LogSearchResponse as GeneratedLogSearchResponse } from '$lib/memorypack/LogSearchResponse';
import { LogAggregateRequest as GeneratedLogAggregateRequest } from '$lib/memorypack/LogAggregateRequest';
import { LogAggregateBucket as GeneratedLogAggregateBucket } from '$lib/memorypack/LogAggregateBucket';
import { LogAggregateResponse as GeneratedLogAggregateResponse } from '$lib/memorypack/LogAggregateResponse';
import { LogAttributeKeysRequest as GeneratedLogAttributeKeysRequest } from '$lib/memorypack/LogAttributeKeysRequest';
import { LogAttributeKeysResponse as GeneratedLogAttributeKeysResponse } from '$lib/memorypack/LogAttributeKeysResponse';
import { LogValueDistributionRequest as GeneratedLogValueDistributionRequest } from '$lib/memorypack/LogValueDistributionRequest';
import { LogValueDistributionResponse as GeneratedLogValueDistributionResponse } from '$lib/memorypack/LogValueDistributionResponse';
import { LogQlQueryRequest as GeneratedLogQlQueryRequest } from '$lib/memorypack/LogQlQueryRequest';
import { LogQlQueryResponse as GeneratedLogQlQueryResponse } from '$lib/memorypack/LogQlQueryResponse';
import { LogPatternRequest as GeneratedLogPatternRequest } from '$lib/memorypack/LogPatternRequest';
import { LogPatternResponse as GeneratedLogPatternResponse } from '$lib/memorypack/LogPatternResponse';
import { ResourceNodeDto as GeneratedResourceNodeDto } from '$lib/memorypack/ResourceNodeDto';
import { ResourceGraphSnapshot as GeneratedResourceGraphSnapshot } from '$lib/memorypack/ResourceGraphSnapshot';
import { HostStatsSnapshot as GeneratedHostStatsSnapshot } from '$lib/memorypack/HostStatsSnapshot';
import { HostStatsHistoryPoint as GeneratedHostStatsHistoryPoint } from '$lib/memorypack/HostStatsHistoryPoint';

/** Falls back to Flare.Api's fixed standalone dev port (see src/Flare.Api/Properties/launchSettings.json). */
export const API_BASE_URL = env.PUBLIC_API_URL ?? 'http://localhost:5085';

/** `Accept`/`Content-Type` value that opts a request in to Flare.Api's MemoryPack encoding (see `Flare.Api/Json/ApiSerialization.cs`) instead of its unconditional JSON default (ADR-0015). */
export const MEMORYPACK_CONTENT_TYPE = 'application/x-memorypack';

/** Headers for a MemoryPack request with no body (a plain `GET`) - only `Accept` matters. */
export function memoryPackAcceptHeaders(): HeadersInit {
	return { Accept: MEMORYPACK_CONTENT_TYPE };
}

/** Headers for a MemoryPack request that also sends a MemoryPack-encoded body. */
export function memoryPackRequestHeaders(): HeadersInit {
	return { 'Content-Type': MEMORYPACK_CONTENT_TYPE, Accept: MEMORYPACK_CONTENT_TYPE };
}

/**
 * Wraps a MemoryPack-serialized `Uint8Array` (every generated/hand-written class's
 * `.serialize()` return value) as a `fetch` `body`. TypeScript 6's DOM lib types `Uint8Array`
 * as the generic `Uint8Array<ArrayBufferLike>` but `BodyInit` still only accepts the
 * non-generic form, so passing one directly is a type error even though `fetch` accepts a
 * `Uint8Array` at runtime just fine - this only satisfies the type checker.
 */
export function memoryPackBody(bytes: Uint8Array): BodyInit {
	return bytes as BodyInit;
}

/**
 * `fetch` wrapper every `lib/*-api.ts` module calls instead of the global `fetch` -
 * `credentials: 'include'` is required for the session cookie (see
 * `lib/auth/state.svelte.ts`) to actually be sent, since the dashboard and Flare.Api are
 * different origins even in docker-compose (different ports). Same signature as `fetch`
 * itself, so every existing call site's URL-building/options stay exactly as they were -
 * only the function name changes.
 */
export async function apiFetch(input: string, init: RequestInit = {}): Promise<Response> {
	return fetch(input, { ...init, credentials: 'include' });
}

// ---- Shared filter shape (LogFilter.cs) ----------------------------------
//
// Migrated (Phase 2 of docs-internal/investigations/memorypack-serialization-migration-scope.md)
// to MemoryPack. `LogFilter`/`LogEventDto` and every request/response type below are
// hand-written (`$lib/memorypack/`) - `LogFilter.From`/`To` are `DateTimeOffset?` and
// `LogEventDto.Timestamp`/`ObservedTimestamp`/`IngestedAt` are `DateTimeOffset` - see
// `$lib/memorypack/date-time-offset.ts`'s header comment. `LogAttributeKeyInfo`/
// `LogAttributeKeysResponse` are the one clean pair in this section and use real generated
// classes. Enum fields (`bag`, `groupBy`, `kind`) convert through
// `$lib/memorypack/enums.ts`'s ordinal↔string adapters, same reasoning `auth-api.ts`
// documents for `UserRole`.

export type AttributeBag = 'Log' | 'Resource' | 'Scope';

export interface AttributeFilter {
	bag: AttributeBag;
	key: string;
	value: string;
}

export interface LogFilter {
	from?: string;
	to?: string;
	services?: string[];
	severityNumbers?: number[];
	traceId?: string;
	spanId?: string;
	patternId?: string;
	search?: string;
	attributes?: AttributeFilter[];
}

// ---- Log event DTO (LogEventDto.cs) ---------------------------------------

export interface LogEventDto {
	eventId: string;
	timestamp: string;
	observedTimestamp: string;
	traceId: string;
	spanId: string;
	traceFlags: number;
	severityText: string;
	severityNumber: number;
	serviceName: string;
	body: string;
	resourceSchemaUrl: string;
	resourceAttributes: Record<string, string>;
	scopeSchemaUrl: string;
	scopeName: string;
	scopeVersion: string;
	scopeAttributes: Record<string, string>;
	logAttributes: Record<string, string>;
	eventName: string;
	patternId: string;
	patternTemplate: string;
	/**
	 * Enclosing span's duration in nanoseconds. `System.Text.Json` has no
	 * `DefaultIgnoreCondition` configured for this context, so an unset `ulong?` on the
	 * backend serializes as an explicit JSON `null`, not an omitted key - `null`, not
	 * just `undefined`, so callers must check `!= null`, never `!== undefined` alone.
	 * Also `null` for every live-tailed event regardless of `includeSpanDuration`
	 * (live-tail rows never go through the backend's follow-up query - see
	 * LogQueryService.SearchAsync's remarks).
	 */
	spanDurationNano?: number | null;
}

function toLogEventDto(dto: GeneratedLogEventDto): LogEventDto {
	return {
		eventId: dto.eventId,
		timestamp: dto.timestamp.toISOString(),
		observedTimestamp: dto.observedTimestamp.toISOString(),
		traceId: dto.traceId ?? '',
		spanId: dto.spanId ?? '',
		traceFlags: dto.traceFlags,
		severityText: dto.severityText ?? '',
		severityNumber: dto.severityNumber,
		serviceName: dto.serviceName ?? '',
		body: dto.body ?? '',
		resourceSchemaUrl: dto.resourceSchemaUrl ?? '',
		resourceAttributes: dto.resourceAttributes ?? {},
		scopeSchemaUrl: dto.scopeSchemaUrl ?? '',
		scopeName: dto.scopeName ?? '',
		scopeVersion: dto.scopeVersion ?? '',
		scopeAttributes: dto.scopeAttributes ?? {},
		logAttributes: dto.logAttributes ?? {},
		eventName: dto.eventName ?? '',
		patternId: dto.patternId ?? '',
		patternTemplate: dto.patternTemplate ?? '',
		spanDurationNano: dto.spanDurationNano == null ? null : Number(dto.spanDurationNano)
	};
}

function toGeneratedLogFilter(filter: LogFilter | undefined): GeneratedLogFilter {
	return logFilterFromPlain(filter);
}

// ---- POST /api/logs/search (LogSearchRequest.cs / LogSearchResponse) ------

export interface LogSearchRequest {
	filter?: LogFilter;
	cursor?: string;
	pageSize?: number;
	/** Opt-in: populate each event's `spanDurationNano` via a follow-up query. See LogSearchRequest.cs's remarks. */
	includeSpanDuration?: boolean;
}

export interface LogSearchResponse {
	events: LogEventDto[];
	nextCursor: string | null;
}

export async function searchLogs(request: LogSearchRequest = {}, signal?: AbortSignal): Promise<LogSearchResponse> {
	const dto = new GeneratedLogSearchRequest();
	dto.filter = toGeneratedLogFilter(request.filter);
	dto.cursor = request.cursor ?? null;
	dto.pageSize = request.pageSize ?? null;
	dto.includeSpanDuration = request.includeSpanDuration ?? false;
	const res = await apiFetch(`${API_BASE_URL}/api/logs/search`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogSearchRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		throw new Error(`POST /api/logs/search failed: ${res.status} ${res.statusText}`);
	}
	const body = GeneratedLogSearchResponse.deserialize(await res.arrayBuffer());
	return {
		events: (body?.events ?? []).map((e) => toLogEventDto(e!)),
		nextCursor: body?.nextCursor ?? null
	};
}

// ---- POST /api/logs/aggregate (LogAggregateRequest.cs / LogAggregateResponse) ----

export type LogAggregateGroupBy = 'None' | 'Service' | 'Level';

export interface LogAggregateRequest {
	filter?: LogFilter;
	bucketWidthSeconds: number;
	groupBy?: LogAggregateGroupBy;
}

export interface LogAggregateBucket {
	bucketStart: string;
	groupKey: string | null;
	count: number;
}

export interface LogAggregateResponse {
	buckets: LogAggregateBucket[];
}

function toLogAggregateBucket(dto: GeneratedLogAggregateBucket): LogAggregateBucket {
	return { bucketStart: dto.bucketStart.toISOString(), groupKey: dto.groupKey, count: dto.count };
}

export async function aggregateLogs(request: LogAggregateRequest, signal?: AbortSignal): Promise<LogAggregateResponse> {
	const dto = new GeneratedLogAggregateRequest();
	dto.filter = toGeneratedLogFilter(request.filter);
	dto.bucketWidthSeconds = request.bucketWidthSeconds;
	dto.groupBy = logAggregateGroupByFromString(request.groupBy ?? 'None');
	const res = await apiFetch(`${API_BASE_URL}/api/logs/aggregate`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogAggregateRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		throw new Error(`POST /api/logs/aggregate failed: ${res.status} ${res.statusText}`);
	}
	const body = GeneratedLogAggregateResponse.deserialize(await res.arrayBuffer());
	return { buckets: (body?.buckets ?? []).map((b) => toLogAggregateBucket(b!)) };
}

// ---- POST /api/logs/numeric-attribute-keys, POST /api/logs/value-distribution ---------
// (LogValueDistributionRequest.cs) - the Logs page's "Value distribution" chart: pick any
// numeric LogAttributes key (there's no first-class duration field - see Planning.md's
// "no duration/p95 in v1" rationale on the Patterns feature for why that's deliberate) and
// see its values scatter-plotted over time. The key list and the sampled points are two
// separate calls so switching the picker doesn't re-run attribute discovery.

export interface LogAttributeKeysRequest {
	filter?: LogFilter;
}

export interface LogAttributeKeyInfo {
	key: string;
	numericCount: number;
}

export interface LogAttributeKeysResponse {
	keys: LogAttributeKeyInfo[];
}

export async function getLogAttributeKeys(
	request: LogAttributeKeysRequest = {},
	signal?: AbortSignal
): Promise<LogAttributeKeysResponse> {
	const dto = new GeneratedLogAttributeKeysRequest();
	dto.filter = toGeneratedLogFilter(request.filter);
	const res = await apiFetch(`${API_BASE_URL}/api/logs/numeric-attribute-keys`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogAttributeKeysRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		throw new Error(`POST /api/logs/numeric-attribute-keys failed: ${res.status} ${res.statusText}`);
	}
	const body = GeneratedLogAttributeKeysResponse.deserialize(await res.arrayBuffer());
	return {
		keys: (body?.keys ?? []).map((k) => ({ key: k!.key ?? '', numericCount: Number(k!.numericCount) }))
	};
}

export interface LogValueDistributionRequest {
	filter?: LogFilter;
	attributeKey: string;
	sampleSize?: number;
}

export interface LogValueDistributionPoint {
	timestamp: string;
	value: number;
}

export interface LogValueDistributionResponse {
	points: LogValueDistributionPoint[];
}

export async function getLogValueDistribution(
	request: LogValueDistributionRequest,
	signal?: AbortSignal
): Promise<LogValueDistributionResponse> {
	const dto = new GeneratedLogValueDistributionRequest();
	dto.filter = toGeneratedLogFilter(request.filter);
	dto.attributeKey = request.attributeKey;
	dto.sampleSize = request.sampleSize ?? 4000;
	const res = await apiFetch(`${API_BASE_URL}/api/logs/value-distribution`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogValueDistributionRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		throw new Error(`POST /api/logs/value-distribution failed: ${res.status} ${res.statusText}`);
	}
	const body = GeneratedLogValueDistributionResponse.deserialize(await res.arrayBuffer());
	return {
		points: (body?.points ?? []).map((p) => ({ timestamp: p!.timestamp.toISOString(), value: p!.value }))
	};
}

// ---- POST /api/logs/query (LogQlQueryRequest.cs) --------------------------
// The Logs page's SQL-query-row feature - a constrained SQL-like grammar
// (`select count(*)|* from stream [where ...] [group by time(1h)[, service|level]]`)
// parsed and translated server-side (see Flare.Api's Query/LogQl/LogQlParser.cs for the
// grammar), never passed through to ClickHouse as raw text. `from`/`to` are the page's
// *current time range* (same resolution VolumeChart.svelte's own currentRange() does) -
// not part of the query text. The toolbar's service/severity/search filters are
// deliberately not applied here; the query's own `where` clause is the only filter.

export type LogQlResultKind = 'Count' | 'Series' | 'Rows' | 'Table';

export interface LogQlQueryRequest {
	query: string;
	from?: string;
	to?: string;
}

export interface LogQlQueryResponse {
	kind: LogQlResultKind;
	/** Count kind only - a plain count(*)/avg(...)/sum(...) result. Fractional for avg(). */
	count: number | null;
	buckets: LogAggregateBucket[] | null;
	events: LogEventDto[] | null;
	/** Table kind only - the selected columns' display names (e.g. `select Service, Body ...`), in select order. */
	columns: string[] | null;
	/** Table kind only - each row's cell values, stringified, aligned with `columns`. */
	rows: string[][] | null;
	hasMoreRows: boolean;
}

/**
 * Unlike every other function in this file, a non-OK response here reads the JSON
 * `ProblemDetails` body (`Results.Problem(ex.Message, ...)` server-side - see
 * LogsEndpoints.HandleQlQueryAsync) and throws its `detail`/`title` instead of a generic
 * "status statusText" string - a parser error like "Unknown column 'Sevrity'" needs to
 * reach SqlQueryRow.svelte verbatim, not as "POST /api/logs/query failed: 400 Bad Request".
 */
export async function runLogQlQuery(request: LogQlQueryRequest, signal?: AbortSignal): Promise<LogQlQueryResponse> {
	const dto = new GeneratedLogQlQueryRequest();
	dto.query = request.query;
	dto.from = request.from == null ? null : new Date(request.from);
	dto.to = request.to == null ? null : new Date(request.to);
	const res = await apiFetch(`${API_BASE_URL}/api/logs/query`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogQlQueryRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		// A parser-error response is always plain JSON ProblemDetails (Results.Problem
		// server-side, unaffected by the Accept header - ApiSerialization only drives the
		// success path) - never MemoryPack, regardless of what this request asked for.
		let message = `POST /api/logs/query failed: ${res.status} ${res.statusText}`;
		try {
			const problem = await res.json();
			message = problem?.detail || problem?.title || message;
		} catch {
			// Body wasn't JSON (or was empty) - fall back to the generic message above.
		}
		throw new Error(message);
	}
	const body = GeneratedLogQlQueryResponse.deserialize(await res.arrayBuffer());
	if (body == null) {
		throw new Error('Empty response body decoding LogQlQueryResponse.');
	}
	return {
		kind: logQlResultKindToString(body.kind),
		count: body.count,
		buckets: body.buckets == null ? null : body.buckets.map((b) => toLogAggregateBucket(b!)),
		events: body.events == null ? null : body.events.map((e) => toLogEventDto(e!)),
		columns: body.columns == null ? null : body.columns.map((c) => c ?? ''),
		rows: body.rows == null ? null : body.rows.map((row) => (row ?? []).map((cell) => cell ?? '')),
		hasMoreRows: body.hasMoreRows
	};
}

// ---- POST /api/logs/patterns (LogPatternModels.cs) -------------------------
//
// Ranked Drain-cluster ("log pattern detection") view - "GET /api/orders/123" and
// "GET /api/orders/456" collapse into one template row, ranked by occurrence count. No
// duration/p95 (logs have no duration field - see Planning.md's rationale); pairs with
// `LogFilter.patternId` for drilling from a pattern row into the Logs Explorer.

export interface LogPatternRequest {
	filter?: LogFilter;
	topN?: number;
}

export interface LogPatternRow {
	patternId: string;
	template: string;
	count: number;
	errorCount: number;
	firstSeen: string;
	lastSeen: string;
}

export interface LogPatternResponse {
	patterns: LogPatternRow[];
}

export async function getPatterns(request: LogPatternRequest = {}, signal?: AbortSignal): Promise<LogPatternResponse> {
	const dto = new GeneratedLogPatternRequest();
	dto.filter = toGeneratedLogFilter(request.filter);
	dto.topN = request.topN ?? null;
	const res = await apiFetch(`${API_BASE_URL}/api/logs/patterns`, {
		method: 'POST',
		headers: memoryPackRequestHeaders(),
		body: memoryPackBody(GeneratedLogPatternRequest.serialize(dto)),
		signal
	});
	if (!res.ok) {
		throw new Error(`POST /api/logs/patterns failed: ${res.status} ${res.statusText}`);
	}
	const body = GeneratedLogPatternResponse.deserialize(await res.arrayBuffer());
	return {
		patterns: (body?.patterns ?? []).map((p) => ({
			patternId: p!.patternId ?? '',
			template: p!.template ?? '',
			count: Number(p!.count),
			errorCount: Number(p!.errorCount),
			firstSeen: p!.firstSeen.toISOString(),
			lastSeen: p!.lastSeen.toISOString()
		}))
	};
}

// ---- GET /api/logs/tail (WebSocket, LogTailMessages.cs) -------------------
//
// Enum values on the wire are PascalCase (the C# member name as-is) - LogsJsonContext/
// LogTailJsonContext's `UseStringEnumConverter` has no naming policy applied to it, only
// `PropertyNamingPolicy` (which affects property names like "type"/"filter", not enum
// values). Confirmed against a real running connection, not assumed - the deserializer on
// the *client message* side is case-insensitive so a lowercase 'subscribe' is silently
// accepted, but the *server message* side always writes the canonical form, so getting
// this wrong here only breaks receiving, not sending - worth the explicit note since
// that asymmetry makes the bug easy to reintroduce and hard to notice from the client-to-server side alone.

export type LogTailClientMessage =
	| { type: 'Subscribe'; filter: LogFilter }
	| { type: 'Pause' }
	| { type: 'Resume' };

export type LogTailServerMessage =
	| { type: 'Event'; event: LogEventDto }
	| { type: 'Dropped'; droppedCount: number }
	| { type: 'Error'; error: string };

export type LiveTailStatus = 'connecting' | 'open' | 'closed' | 'error';

export interface LiveTailHandlers {
	onStatusChange?: (status: LiveTailStatus) => void;
	onEvent?: (event: LogEventDto) => void;
	onDropped?: (droppedCount: number) => void;
	onError?: (error: string) => void;
}

/** Handle returned by {@link connectLiveTail} - lets a caller re-subscribe with a new filter or pause/resume without reconnecting the socket. */
export interface LiveTailConnection {
	/** (Re)subscribes, replacing any previous filter. Queued if the socket hasn't finished connecting yet. */
	subscribe(filter: LogFilter): void;
	pause(): void;
	resume(): void;
	close(): void;
}

/**
 * Opens the live-tail WebSocket and sends an initial `subscribe` once connected.
 * `pendingFilter` tracks the most recently requested filter so a `subscribe()` call that
 * arrives before the handshake completes isn't lost - the `open` handler always sends
 * whatever is current at that point, not just the filter passed in here.
 */
export function connectLiveTail(filter: LogFilter, handlers: LiveTailHandlers): LiveTailConnection {
	const wsUrl = `${API_BASE_URL.replace(/^http/, 'ws')}/api/logs/tail`;
	const socket = new WebSocket(wsUrl);
	let pendingFilter = filter;

	handlers.onStatusChange?.('connecting');

	function send(message: LogTailClientMessage) {
		if (socket.readyState === WebSocket.OPEN) {
			socket.send(JSON.stringify(message));
		}
	}

	socket.addEventListener('open', () => {
		handlers.onStatusChange?.('open');
		send({ type: 'Subscribe', filter: pendingFilter });
	});

	socket.addEventListener('message', (ev) => {
		const message: LogTailServerMessage = JSON.parse(ev.data);
		switch (message.type) {
			case 'Event':
				handlers.onEvent?.(message.event);
				break;
			case 'Dropped':
				handlers.onDropped?.(message.droppedCount);
				break;
			case 'Error':
				handlers.onError?.(message.error);
				break;
		}
	});

	socket.addEventListener('close', () => handlers.onStatusChange?.('closed'));
	socket.addEventListener('error', () => handlers.onStatusChange?.('error'));

	return {
		subscribe(newFilter) {
			pendingFilter = newFilter;
			send({ type: 'Subscribe', filter: newFilter });
		},
		pause() {
			send({ type: 'Pause' });
		},
		resume() {
			send({ type: 'Resume' });
		},
		close() {
			socket.close();
		}
	};
}

// ---- GET /api/resources/snapshot + GET /api/resources/watch (ResourceGraphDto.cs) ----
//
// Resources page - see docs/standalone.md#resources-page-optional-docker-access and
// docs/aspire-hosting.md. `available: false` means neither topology provider is configured
// (no DockerResources:ProxyUrl / KubernetesResources:Enabled on Flare.Api's side), not "no
// AppHost" - a different, simpler story than LiveTail-adjacent features get elsewhere in
// this file. Exactly one provider is ever expected to actually be configured per deploy -
// see `provider` below - so there's no "pick a backend" UI on this page, just different
// rendering of the one snapshot that comes back. `state`/`health` are PascalCase string enum
// values, same UseStringEnumConverter asymmetry documented above for LogTailServerMessage.

export type ResourceState = 'Unknown' | 'Running' | 'Exited' | 'Restarting' | 'Paused';
export type ResourceHealth = 'Starting' | 'Healthy' | 'Unhealthy';

export interface ResourceNodeDto {
	id: string;
	role: string;
	name: string;
	image: string;
	state: ResourceState;
	health: ResourceHealth | null;
	urls: string[];
	/** `'Container'` for every Docker-provider node. The Kubernetes provider emits `'Namespace'`/`'Deployment'`/`'Pod'`/`'Service'` - not a closed union on the C# side either, so treat unrecognized values as the generic case rather than exhaustively switching. See `ResourceNodeDto.cs`'s remarks. */
	kind: string;
	/** This node's parent in the Kubernetes provider's hierarchy - `null` for every Docker node (flat graph) and for the Namespace root itself. See `ResourceNodeDto.cs`'s remarks. */
	parentId: string | null;
}

export interface ResourceEdgeDto {
	/** Despite the name, any graph node id - a Docker `flare.role` value, a Kubernetes Pod's `role` (see `ResourceNodeDto.role`'s Kubernetes-provider remarks), or a producer's `ProducerServiceDto.id`. See `ResourceEdgeDto.cs`'s remarks. */
	sourceRole: string;
	targetRole: string;
	relationshipType: string;
}

/** A service observed sending telemetry into `ingest` recently - sourced from ClickHouse, not Docker/Kubernetes, so it can represent a producer with no footprint in either (e.g. an `AddProject` resource under Aspire's dev-loop). See `ResourceGraphDto.cs`'s remarks. */
export interface ProducerServiceDto {
	id: string;
	serviceName: string;
	lastSeenAt: string;
}

export interface ResourceGraphSnapshot {
	available: boolean;
	unavailableReason: string | null;
	nodes: ResourceNodeDto[];
	edges: ResourceEdgeDto[];
	producers: ProducerServiceDto[];
	updatedAt: string | null;
	/** Which topology provider produced this snapshot, or `null` when neither is configured (same state as `available: false`) - see `ResourceGraphSnapshot.cs`'s remarks. */
	provider: 'Docker' | 'Kubernetes' | null;
}

function toResourceNodeDto(dto: GeneratedResourceNodeDto): ResourceNodeDto {
	return {
		id: dto.id ?? '',
		role: dto.role ?? '',
		name: dto.name ?? '',
		image: dto.image ?? '',
		state: resourceStateToString(dto.state),
		health: dto.health == null ? null : resourceHealthToString(dto.health),
		urls: (dto.urls ?? []).map((u) => u ?? ''),
		kind: dto.kind ?? '',
		parentId: dto.parentId
	};
}

function toResourceGraphSnapshot(dto: GeneratedResourceGraphSnapshot): ResourceGraphSnapshot {
	return {
		available: dto.available,
		unavailableReason: dto.unavailableReason,
		nodes: (dto.nodes ?? []).map((n) => toResourceNodeDto(n!)),
		edges: (dto.edges ?? []).map((e) => ({
			sourceRole: e!.sourceRole ?? '',
			targetRole: e!.targetRole ?? '',
			relationshipType: e!.relationshipType ?? ''
		})),
		producers: (dto.producers ?? []).map((p) => ({
			id: p!.id ?? '',
			serviceName: p!.serviceName ?? '',
			lastSeenAt: p!.lastSeenAt.toISOString()
		})),
		updatedAt: dto.updatedAt?.toISOString() ?? null,
		provider: dto.provider as 'Docker' | 'Kubernetes' | null
	};
}

/**
 * `/watch`'s messages are plain JSON (out of scope - the 3 WebSocket endpoints have no
 * per-message `Accept` to negotiate against, see ADR-0015/ADR-0016), but this snapshot GET
 * is now MemoryPack - both decode into the same `ResourceGraphSnapshot` shape, so
 * `connectResourcesWatch` below is unaffected.
 */
export async function fetchResourceSnapshot(signal?: AbortSignal): Promise<ResourceGraphSnapshot> {
	const res = await apiFetch(`${API_BASE_URL}/api/resources/snapshot`, { headers: memoryPackAcceptHeaders(), signal });
	if (!res.ok) {
		throw new Error(`GET /api/resources/snapshot failed: ${res.status} ${res.statusText}`);
	}
	const dto = GeneratedResourceGraphSnapshot.deserialize(await res.arrayBuffer());
	if (dto == null) {
		throw new Error('Empty response body decoding ResourceGraphSnapshot.');
	}
	return toResourceGraphSnapshot(dto);
}

export type ResourcesWatchStatus = 'connecting' | 'open' | 'closed' | 'error';

export interface ResourcesWatchHandlers {
	onStatusChange?: (status: ResourcesWatchStatus) => void;
	onSnapshot?: (snapshot: ResourceGraphSnapshot) => void;
}

/** Handle returned by {@link connectResourcesWatch}. Push-only on the wire (no client->server messages, unlike {@link LiveTailConnection}) - the graph isn't filtered, so there's nothing to subscribe/pause/resume. */
export interface ResourcesWatchConnection {
	close(): void;
}

/**
 * Opens the resources-watch WebSocket - every message received is a complete, fresh
 * {@link ResourceGraphSnapshot} (not an incremental diff or a discriminated-union
 * envelope like {@link LogTailServerMessage}), pushed once per `DockerContainerPoller`
 * tick on the server plus immediately on connect.
 */
export function connectResourcesWatch(handlers: ResourcesWatchHandlers): ResourcesWatchConnection {
	const wsUrl = `${API_BASE_URL.replace(/^http/, 'ws')}/api/resources/watch`;
	const socket = new WebSocket(wsUrl);

	handlers.onStatusChange?.('connecting');

	socket.addEventListener('open', () => handlers.onStatusChange?.('open'));
	socket.addEventListener('message', (ev) => {
		const snapshot: ResourceGraphSnapshot = JSON.parse(ev.data);
		handlers.onSnapshot?.(snapshot);
	});
	socket.addEventListener('close', () => handlers.onStatusChange?.('closed'));
	socket.addEventListener('error', () => handlers.onStatusChange?.('error'));

	return {
		close() {
			socket.close();
		}
	};
}

// ---- Resources page: Host overview panel (HostStatsSnapshot.cs) ----------

/** Mirrors `Model/HostStatsSnapshot.cs` - see that file's own remarks for each field. */
export interface HostStatsSnapshot {
	available: boolean;
	unavailableReason: string | null;
	cpuUsagePercent: number;
	cpuCoreCount: number;
	loadAverage1m: number;
	perCoreUsagePercent: number[];
	memoryTotalBytes: number;
	memoryUsedBytes: number;
	memoryAvailableBytes: number;
	swapTotalBytes: number;
	swapUsedBytes: number;
	diskTotalBytes: number;
	diskUsedBytes: number;
	diskAvailableBytes: number;
	diskGrowthBytesPerDay: number | null;
	diskGrowthWindowHours: number;
	diskReadBytesPerSecond: number;
	diskWriteBytesPerSecond: number;
	networkBytesPerSecond: number;
	networkRxBytesPerSecond: number;
	networkTxBytesPerSecond: number;
	networkPacketsPerSecond: number;
	uptimeSeconds: number;
	updatedAt: string | null;
}

function toHostStatsSnapshot(dto: GeneratedHostStatsSnapshot): HostStatsSnapshot {
	return {
		available: dto.available,
		unavailableReason: dto.unavailableReason,
		cpuUsagePercent: dto.cpuUsagePercent,
		cpuCoreCount: dto.cpuCoreCount,
		loadAverage1m: dto.loadAverage1m,
		perCoreUsagePercent: dto.perCoreUsagePercent ?? [],
		memoryTotalBytes: Number(dto.memoryTotalBytes),
		memoryUsedBytes: Number(dto.memoryUsedBytes),
		memoryAvailableBytes: Number(dto.memoryAvailableBytes),
		swapTotalBytes: Number(dto.swapTotalBytes),
		swapUsedBytes: Number(dto.swapUsedBytes),
		diskTotalBytes: Number(dto.diskTotalBytes),
		diskUsedBytes: Number(dto.diskUsedBytes),
		diskAvailableBytes: Number(dto.diskAvailableBytes),
		diskGrowthBytesPerDay: dto.diskGrowthBytesPerDay,
		diskGrowthWindowHours: dto.diskGrowthWindowHours,
		diskReadBytesPerSecond: dto.diskReadBytesPerSecond,
		diskWriteBytesPerSecond: dto.diskWriteBytesPerSecond,
		networkBytesPerSecond: dto.networkBytesPerSecond,
		networkRxBytesPerSecond: dto.networkRxBytesPerSecond,
		networkTxBytesPerSecond: dto.networkTxBytesPerSecond,
		networkPacketsPerSecond: dto.networkPacketsPerSecond,
		uptimeSeconds: dto.uptimeSeconds,
		updatedAt: dto.updatedAt?.toISOString() ?? null
	};
}

/** `/watch`'s messages are plain JSON (out of scope, same reasoning as the Docker resource graph's `/watch`), but this snapshot GET is now MemoryPack - both decode into the same `HostStatsSnapshot` shape, so `connectHostStatsWatch` below is unaffected. */
export async function fetchHostStatsSnapshot(signal?: AbortSignal): Promise<HostStatsSnapshot> {
	const res = await apiFetch(`${API_BASE_URL}/api/resources/host/snapshot`, { headers: memoryPackAcceptHeaders(), signal });
	if (!res.ok) {
		throw new Error(`GET /api/resources/host/snapshot failed: ${res.status} ${res.statusText}`);
	}
	const dto = GeneratedHostStatsSnapshot.deserialize(await res.arrayBuffer());
	if (dto == null) {
		throw new Error('Empty response body decoding HostStatsSnapshot.');
	}
	return toHostStatsSnapshot(dto);
}

export type HostStatsWatchStatus = ResourcesWatchStatus;

export interface HostStatsWatchHandlers {
	onStatusChange?: (status: HostStatsWatchStatus) => void;
	onSnapshot?: (snapshot: HostStatsSnapshot) => void;
}

/** Handle returned by {@link connectHostStatsWatch}. Same push-only shape as {@link ResourcesWatchConnection}. */
export interface HostStatsWatchConnection {
	close(): void;
}

/**
 * Opens the host-stats-watch WebSocket - every message received is a complete, fresh
 * {@link HostStatsSnapshot} pushed once per `HostStatsPoller` tick on the server plus
 * immediately on connect. Same shape as {@link connectResourcesWatch}, kept as its own
 * function/connection since it's an independent stream (no shared subscribe/pause
 * protocol, no shared enablement with the Docker resource graph).
 */
export function connectHostStatsWatch(handlers: HostStatsWatchHandlers): HostStatsWatchConnection {
	const wsUrl = `${API_BASE_URL.replace(/^http/, 'ws')}/api/resources/host/watch`;
	const socket = new WebSocket(wsUrl);

	handlers.onStatusChange?.('connecting');

	socket.addEventListener('open', () => handlers.onStatusChange?.('open'));
	socket.addEventListener('message', (ev) => {
		const snapshot: HostStatsSnapshot = JSON.parse(ev.data);
		handlers.onSnapshot?.(snapshot);
	});
	socket.addEventListener('close', () => handlers.onStatusChange?.('closed'));
	socket.addEventListener('error', () => handlers.onStatusChange?.('error'));

	return {
		close() {
			socket.close();
		}
	};
}

/** Mirrors `Model/HostStatsHistoryPoint.cs` - one sample in the Resource trends chart. */
export interface HostStatsHistoryPoint {
	timestamp: string;
	cpuUsagePercent: number;
	memoryUsedPercent: number;
	diskUsedPercent: number;
	networkBytesPerSecond: number;
}

/**
 * The Resource trends chart's backfill - the retained rolling window (default 1h) as of
 * this call, oldest first. No WebSocket counterpart: `HostStatsState` fetches this once on
 * connect, then derives each subsequent point itself from the watch stream it's already
 * receiving (see `$lib/resources/host-stats.svelte.ts`).
 */
export async function fetchHostStatsHistory(signal?: AbortSignal): Promise<HostStatsHistoryPoint[]> {
	const res = await apiFetch(`${API_BASE_URL}/api/resources/host/history`, { headers: memoryPackAcceptHeaders(), signal });
	if (!res.ok) {
		throw new Error(`GET /api/resources/host/history failed: ${res.status} ${res.statusText}`);
	}
	const points = GeneratedHostStatsHistoryPoint.deserializeArray(await res.arrayBuffer());
	return (points ?? []).map((p) => ({
		timestamp: p!.timestamp.toISOString(),
		cpuUsagePercent: p!.cpuUsagePercent,
		memoryUsedPercent: p!.memoryUsedPercent,
		diskUsedPercent: p!.diskUsedPercent,
		networkBytesPerSecond: p!.networkBytesPerSecond
	}));
}
