using System.Text.Json;
using Flare.Api.LiveTail;
using Xunit;

namespace Flare.Api.Tests.LiveTail;

/// <summary>
/// Round-trip tests for <see cref="BufferedLogEventJsonContext"/>, plus a hand-written
/// fixture test proving it parses the exact wire bytes
/// <c>Flare.Ingest.Pipeline.LogEventJsonContext</c> produces - the two aren't
/// project-referenced (see <see cref="BufferedLogEvent"/>'s remarks), so nothing else
/// catches the two silently drifting apart.
/// </summary>
public class BufferedLogEventJsonContextTests
{
    [Fact]
    public void RoundTrips_BufferedLogEvent_WithAllOptionalFieldsPopulated()
    {
        var original = new BufferedLogEvent
        {
            EventId = Guid.NewGuid(),
            Timestamp = new DateTimeOffset(2026, 8, 7, 12, 0, 0, TimeSpan.Zero),
            ObservedTimestamp = new DateTimeOffset(2026, 8, 7, 12, 0, 1, TimeSpan.Zero),
            IngestedAt = new DateTimeOffset(2026, 8, 7, 12, 0, 2, TimeSpan.Zero),
            SeverityNumber = 17,
            SeverityText = "Error",
            Body = "something went wrong",
            TraceId = "abc123",
            SpanId = "def456",
            TraceFlags = 1,
            ServiceName = "flare-ingest",
            ResourceSchemaUrl = "https://opentelemetry.io/schemas/1.0.0",
            ResourceAttributes = new Dictionary<string, string> { ["service.name"] = "flare-ingest" },
            ScopeSchemaUrl = "https://opentelemetry.io/schemas/1.0.0",
            ScopeName = "Flare.Ingest",
            ScopeVersion = "1.0.0",
            ScopeAttributes = new Dictionary<string, string> { ["scope.key"] = "scope-value" },
            LogAttributes = new Dictionary<string, string> { ["http.method"] = "GET", ["http.status_code"] = "500" },
            EventName = "request.failed",
        };

        AssertRoundTrips(original);
    }

    [Fact]
    public void RoundTrips_BufferedLogEvent_WithAllOptionalFieldsNull()
    {
        var original = new BufferedLogEvent
        {
            EventId = Guid.NewGuid(),
            Timestamp = DateTimeOffset.UnixEpoch,
            IngestedAt = DateTimeOffset.UnixEpoch,
            SeverityNumber = 0,
            ResourceAttributes = new Dictionary<string, string>(),
            ScopeAttributes = new Dictionary<string, string>(),
            LogAttributes = new Dictionary<string, string>(),
        };

        AssertRoundTrips(original);
    }

    [Fact]
    public void Deserializes_HandWrittenFixture_MatchingFlareIngestWireFormat()
    {
        // Deliberately hand-written, not generated by serializing a BufferedLogEvent -
        // same field names/casing/values as Flare.Ingest.Tests's
        // LogEventJsonContextTests.RoundTrips_LogEvent_WithAllOptionalFieldsPopulated, so
        // a rename/retype on that side that isn't mirrored here fails this test instead of
        // silently breaking live-tail deserialization in production.
        const string json = """
            {
              "EventId": "11111111-1111-1111-1111-111111111111",
              "Timestamp": "2026-08-07T12:00:00+00:00",
              "ObservedTimestamp": "2026-08-07T12:00:01+00:00",
              "IngestedAt": "2026-08-07T12:00:02+00:00",
              "SeverityNumber": 17,
              "SeverityText": "Error",
              "Body": "something went wrong",
              "TraceId": "abc123",
              "SpanId": "def456",
              "TraceFlags": 1,
              "ServiceName": "flare-ingest",
              "ResourceSchemaUrl": "https://opentelemetry.io/schemas/1.0.0",
              "ResourceAttributes": { "service.name": "flare-ingest" },
              "ScopeSchemaUrl": "https://opentelemetry.io/schemas/1.0.0",
              "ScopeName": "Flare.Ingest",
              "ScopeVersion": "1.0.0",
              "ScopeAttributes": { "scope.key": "scope-value" },
              "LogAttributes": { "http.method": "GET", "http.status_code": "500" },
              "EventName": "request.failed"
            }
            """;

        var bufferedLogEvent = JsonSerializer.Deserialize(json, BufferedLogEventJsonContext.Default.BufferedLogEvent);

        Assert.NotNull(bufferedLogEvent);
        Assert.Equal(Guid.Parse("11111111-1111-1111-1111-111111111111"), bufferedLogEvent.EventId);
        Assert.Equal(new DateTimeOffset(2026, 8, 7, 12, 0, 0, TimeSpan.Zero), bufferedLogEvent.Timestamp);
        Assert.Equal(new DateTimeOffset(2026, 8, 7, 12, 0, 1, TimeSpan.Zero), bufferedLogEvent.ObservedTimestamp);
        Assert.Equal(new DateTimeOffset(2026, 8, 7, 12, 0, 2, TimeSpan.Zero), bufferedLogEvent.IngestedAt);
        Assert.Equal(17, bufferedLogEvent.SeverityNumber);
        Assert.Equal("Error", bufferedLogEvent.SeverityText);
        Assert.Equal("something went wrong", bufferedLogEvent.Body);
        Assert.Equal("abc123", bufferedLogEvent.TraceId);
        Assert.Equal("def456", bufferedLogEvent.SpanId);
        Assert.Equal((byte)1, bufferedLogEvent.TraceFlags);
        Assert.Equal("flare-ingest", bufferedLogEvent.ServiceName);
        Assert.Equal(new Dictionary<string, string> { ["service.name"] = "flare-ingest" }, bufferedLogEvent.ResourceAttributes);
        Assert.Equal(new Dictionary<string, string> { ["scope.key"] = "scope-value" }, bufferedLogEvent.ScopeAttributes);
        Assert.Equal(
            new Dictionary<string, string> { ["http.method"] = "GET", ["http.status_code"] = "500" },
            bufferedLogEvent.LogAttributes);
        Assert.Equal("request.failed", bufferedLogEvent.EventName);
    }

    /// <summary>See <c>Flare.Ingest.Tests</c>'s <c>LogEventJsonContextTests.AssertRoundTrips</c> for why this is field-by-field, not whole-record <c>Equals</c>.</summary>
    private static void AssertRoundTrips(BufferedLogEvent original)
    {
        var json = JsonSerializer.Serialize(original, BufferedLogEventJsonContext.Default.BufferedLogEvent);
        var roundTripped = JsonSerializer.Deserialize(json, BufferedLogEventJsonContext.Default.BufferedLogEvent);

        Assert.NotNull(roundTripped);
        Assert.Equal(original.EventId, roundTripped.EventId);
        Assert.Equal(original.Timestamp, roundTripped.Timestamp);
        Assert.Equal(original.ObservedTimestamp, roundTripped.ObservedTimestamp);
        Assert.Equal(original.IngestedAt, roundTripped.IngestedAt);
        Assert.Equal(original.SeverityNumber, roundTripped.SeverityNumber);
        Assert.Equal(original.SeverityText, roundTripped.SeverityText);
        Assert.Equal(original.Body, roundTripped.Body);
        Assert.Equal(original.TraceId, roundTripped.TraceId);
        Assert.Equal(original.SpanId, roundTripped.SpanId);
        Assert.Equal(original.TraceFlags, roundTripped.TraceFlags);
        Assert.Equal(original.ServiceName, roundTripped.ServiceName);
        Assert.Equal(original.ResourceSchemaUrl, roundTripped.ResourceSchemaUrl);
        Assert.Equal(original.ResourceAttributes, roundTripped.ResourceAttributes);
        Assert.Equal(original.ScopeSchemaUrl, roundTripped.ScopeSchemaUrl);
        Assert.Equal(original.ScopeName, roundTripped.ScopeName);
        Assert.Equal(original.ScopeVersion, roundTripped.ScopeVersion);
        Assert.Equal(original.ScopeAttributes, roundTripped.ScopeAttributes);
        Assert.Equal(original.LogAttributes, roundTripped.LogAttributes);
        Assert.Equal(original.EventName, roundTripped.EventName);
    }
}
