apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flare.secretName" . }}
  labels: {{- include "flare.labels" . | nindent 4 }}
type: Opaque
stringData:
  clickhouse-password: {{ include "flare.password" (dict "root" . "key" "clickhouse-password" "value" .Values.clickhouse.password) | quote }}
  redis-password: {{ include "flare.password" (dict "root" . "key" "redis-password" "value" .Values.redis.password) | quote }}
  postgres-password: {{ include "flare.password" (dict "root" . "key" "postgres-password" "value" .Values.identity.postgres.password) | quote }}
  smtp-password: {{ .Values.email.password | quote }}
  identity-connection-string: {{ .Values.identity.postgres.external.connectionString | quote }}
